-- Additive storage for Telegram conversation history and durable memories.
-- The composite keys keep every row scoped to one external user, chat, and
-- Atlas conversation, even when identifiers happen to overlap.

create table if not exists public.telegram_conversations (
    id bigint generated by default as identity primary key,
    external_user_id text not null,
    chat_id text not null,
    conversation_id text not null,
    atlas_context_active boolean not null default false,
    atlas_context_expires_at timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint telegram_conversations_scope_key
        unique (external_user_id, chat_id, conversation_id)
);

create index if not exists idx_telegram_conversations_chat_updated
    on public.telegram_conversations (external_user_id, chat_id, updated_at desc);

create index if not exists idx_telegram_conversations_active_context
    on public.telegram_conversations (
        external_user_id,
        chat_id,
        atlas_context_expires_at
    )
    where atlas_context_active = true;

create table if not exists public.telegram_messages (
    id bigint generated by default as identity primary key,
    external_user_id text not null,
    chat_id text not null,
    conversation_id text not null,
    role text not null,
    content text not null,
    created_at timestamptz not null default now(),
    constraint telegram_messages_role_check
        check (role in ('system', 'user', 'assistant', 'tool')),
    constraint telegram_messages_conversation_fk
        foreign key (external_user_id, chat_id, conversation_id)
        references public.telegram_conversations (
            external_user_id,
            chat_id,
            conversation_id
        )
        on delete cascade
);

create index if not exists idx_telegram_messages_conversation_created
    on public.telegram_messages (
        external_user_id,
        chat_id,
        conversation_id,
        created_at desc,
        id desc
    );

create table if not exists public.telegram_memories (
    id bigint generated by default as identity primary key,
    external_user_id text not null,
    chat_id text not null,
    conversation_id text not null,
    memory_key text not null,
    content text not null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint telegram_memories_conversation_fk
        foreign key (external_user_id, chat_id, conversation_id)
        references public.telegram_conversations (
            external_user_id,
            chat_id,
            conversation_id
        )
        on delete cascade,
    constraint telegram_memories_scope_key
        unique (external_user_id, chat_id, conversation_id, memory_key)
);

create index if not exists idx_telegram_memories_conversation_updated
    on public.telegram_memories (
        external_user_id,
        chat_id,
        conversation_id,
        updated_at desc
    );

-- The bot uses only the server-side service role. With RLS enabled and no
-- client policies, anon/authenticated clients cannot read or write this data.
alter table public.telegram_conversations enable row level security;
alter table public.telegram_messages enable row level security;
alter table public.telegram_memories enable row level security;
